export const watermark = document.createElement('p');
watermark.textContent = "Image generated by showcase duo by Anthony Martins";
watermark.style.position = 'absolute';
watermark.style.bottom = '1px';
watermark.style.left = '1000px';
watermark.style.backgroundColor = 'rgba(0, 0, 0, 0.5)';
watermark.style.padding = '2px 5px';
watermark.style.borderRadius = '3px';